
services:
  todo-app:
    image: todo-app:latest
    build: .
    ports:
      - "8091:8091"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/todo_app
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=jagrati
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: todo_app
      MYSQL_ROOT_PASSWORD: jagrati
    ports:
      - "3308:3308"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
