# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mytodo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_09f2ea962f624280aaa34e07c33615e3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_de1123e7d294489ca9347f3f981ffd0b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_09f2ea962f624280aaa34e07c33615e3 }}/629708747243.dkr.ecr.us-east-1.amazonaws.com/my-todo-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mytodo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e7bd5568f32841cc9e82dcff51f70afd }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_09f2ea962f624280aaa34e07c33615e3 }}/629708747243.dkr.ecr.us-east-1.amazonaws.com/my-todo-app:${{ github.sha }}'